### ISSUE TITLE
You can't send more than one URL parameter in a URL

### ISSUE THREAD

**Issue by zachfeldman** [csquared/IMGKit#104]
This threw no error but also didn't send any requests to my server. I'm just posting this issue in case anyone else has this problem as it took me 2-3 hours to figure out!

**Comment by Murarius** [comment]
any solution for this problem?

**Comment by zachfeldman** [comment]
Yeah, I control the server I was fetching the data from. So I changed my endpoint to use params in the URL.

For instance, instead of:

example.com/card?id=44&token=jiof42io32

I did

example.com/card/44?token=3j32r2

Hope that helps!

**Comment by Murarius** [comment]
Good solution, Thanks
