### ISSUE TITLE
Providing image size

### ISSUE THREAD

**Issue by novito** [csquared/IMGKit#61]
Is there any feature that would allow IMGKit to receive the desired dimensions of the exported image?

I have an HTML page which is based on just a container with defined width and height, and I just care about the contents of that container for the image.

Is there any way I can specify viewport width/height to IMGKit, so that just that part of the HTML gets exported to PNG?

**Comment by hrideshkumar** [comment]
How can add this parameters. I am using imgkit.from_string(html, fileLocation, {width: 160, height:600}) method.

My requirement is reduce size of saved image.

Thanks.

**Comment by AdityaKannan** [comment]
> How can add this parameters. I am using imgkit.from_string(html, fileLocation, {width: 160, height:600}) method.
> 
> My requirement is reduce size of saved image.
> 
> Thanks.

Hey, you need to specify the width and height attributes in the imgkit options, like so:
`options = {
    'format': 'png',
    'width': '640',
    'height': '480'
    }`
`imgkit.from_file(['htmllocation'], 'imglocation',options=options)`
