### ISSUE TITLE
IMGKit::CommandFailedError

### ISSUE THREAD

**Issue by davidpatters0n** [csquared/IMGKit#65]
So I tried following the basic example of converting a URL to an image. But I seem to get the following: 

``` code
1.9.3-p392 :009 > IMGKit::VERSION
 => "1.4.1" 
1.9.3-p392 :010 > kit = IMGKit.new('http://google.com', quality: 40, zoom: 0.2)
 => #<IMGKit:0x0000000617cc70 @source=http://google.com, @stylesheets=[], @options={:height=>1000, :quality=>40, :zoom=>0.2}> 
1.9.3-p392 :011 > img = kit.to_img(:png) and 'good'
IMGKit::CommandFailedError: Command failed: /usr/local/bin/wkhtmltoimage --height 1000 --quality 40 --zoom 0.2 --format png http://google.com -: Loading page (1/2)
QSslSocket: cannot resolve SSLv2_client_method               ] 10%
QSslSocket: cannot resolve SSLv2_server_method
Rendering (2/2)                                                    
QPixmap: Cannot create a QPixmap when no GUI is being used   ] 25%
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used
QPixmap: Cannot create a QPixmap when no GUI is being used

        from /home/david/.rvm/gems/ruby-1.9.3-p392/gems/imgkit-1.4.1/lib/imgkit/imgkit.rb:111:in `to_img'
        from (irb):11
        from /home/david/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
        from /home/david/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
        from /home/david/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I did also try following this comment: https://github.com/csquared/IMGKit/issues/32#issuecomment-8863340

**Comment by joaovpmamede** [comment]
In my case I can't just put the action to a delayed job because the client is editing some fields that will trigger the image rendering and needs the ajax response asap.
Should I use a different wkhtmltoimage version?
Right now I'm with:

wkhtmltoimage 0.12.1 (with patched qt)

**Comment by nalidixic** [comment]
@joaovpmamede Maybe open up a new issue. This one is pretty dated now.

**Comment by nicholasklick** [comment]
@joaovpmamede 

Your ajax response will not be immediate depending on the img you are generating. In my case I had to show a temporary `Loading...` ui element while the image is generated.

A different wkhtmltoimage version will not change the image generation speed much since it is rendering the html in a headless browser and then writing the img to a file usually. Even if you try running `wkhtmltoimage` in the cmd line directly it takes at least 2-3 seconds.

fyi I am using wkhtmltoimage 0.12.1 (with patched qt)

**Comment by joaovpmamede** [comment]
@nicholasklick 

Yup it won't be immediate, it will block until the image is generated and when finished, the action is fulfilled and will respond.

Problem is, if I get any error on the template I'm rendering it won't timeout, it won't show any error, nothing...and I'm trying to figure it out what to do when it hangs. Restart rails won't help either.

**Comment by nicholasklick** [comment]
@joaovpmamede <https://github.com/joaovpmamede>

You getting the same error as shown above? Not clear by your message.

I would detect whether the file was generated correctly on the server and
if it fails it should be handled in an Ajax fail block or success=false or
something. Seems like you have some options.

I decided not to generate the img in a background job for this reason
exactly.

I am actually using this to capture complex highchart images which are then
uploaded to s3.

**Comment by joaovpmamede** [comment]
@nicholasklick 

Sorry my mistake of bringing my issue (that is kinda of different than the above) to here.
Well, I'll try to figure it out what's happening when the process just hangs without any reason/warning.
