### ISSUE TITLE
Pass in additional parameters to 'wkhtmltoimage' command

### ISSUE THREAD

**Issue by R3dy** [csquared/IMGKit#77]
I am getting the following error.  While trying to call

``` Ruby
img = screenshot.to_img(:jpeg)
```

<pre>
IMGKit::CommandFailedError: Command failed: /Users/rdavis/bin/wkhtmltoimage --height 600 --quality 60 --width 800 --format jpg http://1.1.1.1:80 -: Loading page (1/2)
Error: Failed loading page http://1.1.1.1:80 (sometimes it will work just to ignore this error with --load-error-handling ignore)
from /Users/rdavis/.rvm/gems/ruby-2.1.2/gems/imgkit-1.6.0/lib/imgkit/imgkit.rb:113:in `to_img'
</pre>

I am particularly interested in this portion of the error.

<pre>
(sometimes it will work just to ignore this error with --load-error-handling ignore)
</pre>

Is there a way I can pass the '--load-error-handling ignore' option to the wkhtmltoimage command from my script?

Thanks!!

**Comment by drewB** [comment]
You should be able to simply do:

IMGKit.new(..., 'load-error-handling ignore' => true)

**Comment by adamb0mb** [comment]
Just pinging on this. It can probably be closed.

**Comment by R3dy** [comment]
Hash forgot all about this.  Sorry folks!
