### ISSUE TITLE
Not sure the url has been change? 

### ISSUE THREAD

**Issue by andyyou** [csquared/IMGKit#80]
I am trying to install wkhtmltoimage but got some problem as follow

```
/Users/x/.rvm/gems/ruby-2.1.5/gems/imgkit-1.6.0/bin/imgkit:12:in `detect_architecture': Use RbConfig instead of obsolete and deprecated Config.
/Users/x/.rvm/gems/ruby-2.1.5/gems/imgkit-1.6.0/bin/imgkit:12:in `detect_architecture': Use RbConfig instead of obsolete and deprecated Config.
rm: /usr/local/bin/wkhtmltoimage: No such file or directory
Sorry, I couldn't find the binary for your architecture (OSX)
  at http://code.google.com/p/wkhtmltopdf/downloads/list?can=1
Please go to that page, unzip the appropriate binary, and install
```

**Comment by andyyou** [comment]
I suspect the google project url causes this problem

**Comment by csquared** [comment]
Damn -- yeah they change this every year or so on me.  You can download it by hand in the meantime. If you do, would you mind sharing the URL?

**Comment by andyyou** [comment]
I'm not sure which version is correct [here](http://wkhtmltopdf.org/downloads.html)

Seems after I download by hand and installed I still can't use Imgkit in my mac. :(

**Comment by CloCkWeRX** [comment]
It looks like http://wkhtmltopdf.org/obsolete-downloads.html is the last place a dedicated wkhtmltoimage binary was provided.

It now provides a generic wkhtmltox; but I'm not sure a wkhtmltoimage binary is included (wkhtmltopdf is)

**Comment by CloCkWeRX** [comment]
Ah, imgkit helpfully decided to remove various binaries that my package manager was in charge of; then failed half way through leaving a broken installation.
