### ISSUE TITLE
IMGKit hangs when calling to_img(:jpg) method with rails s

### ISSUE THREAD

**Issue by liqites** [csquared/IMGKit#84]
## Environment
```
ruby -> 2.0.0-p247
rails -> 4.0.13
OS X -> 10.10.4
imgkit -> 1.6.1
wkhtmltoimage -> 0.12.2.1
```
**Start server with `rails s`**
## Using in Controller
```ruby
def to_image
  html_string = render_to_string("images/index.html.erb") # a very simple page with a <p></p>
  kit = IMGKit.new(html_string)
  kit.to_file("tmp/xxx.kpg") #hangs here!!!
  ...
end
```

## Additional Information
- Working if putting the code into Sidekiq job.
- Working if starting server using Unicorn with multiple workers. But single worker hangs!
- Working in Rails Console.

**Comment by liqites** [comment]
Sorry man, stupid question.
I think reason is bellow:
- runing rails with `rails s` --> single process
- runing a child process with IMGKit to call command `wkhtmltoimage`
- `wkhtmltoimage` will load page, which means loading resource from `rails` server.
- but `rails`process is waiting `wkhtmltoimage` process  to return to response my request.
- so no `rails` process can handle the `wkhtmltoimage` loading resource request.

**Dead Lock, LOL**

**Comment by phackwer** [comment]
I don't get it?! Is it solved? How?! I'm having similar problems here.

**Comment by liqites** [comment]
@phackwer 
That's because at that time, year 2015. My `rails s` only starts in single process mode.

Assumes that the only process called `Process A`, the progress will be like this:

1. Client send request --> `Process A` handle the request.
2. In  `Process A`, it calls `IMGKit` to send another request to my `rails` server to render view for generating image and it waits.
3. Since `Process A` is waiting and I do not have another process to handle the `IMGKit` request.
4. My server hangs because of this.

### Solution

You need to start your `rails s` server **MULTIPLE PROCESSES** or **MULTIPLE THREADS** mode

**Comment by liqites** [comment]
@phackwer

**Comment by liqites** [comment]
@phackwer 

* If the reason your QA server hangs is not have enough process to handle requests.
* The easy way to determine the problem is calling the  IMGKit code request an url not point to your system, like google.com,  to generate image. 
* If it still hangs, that's not the problem like mine.
* If it not hangs, that's maybe caused by lacking of enough processes.

Below is some more info I need to know for figuring out the question.

## 1. You said IMGKit code works smooth in locally development mode

**My Question is:**
- What url does your IMGKit code request to generate image ? 
- Where does the url point to?
- Does the url point to an `action` in `controller` of your local development server?
If so, it still has a chance of hangs.
If not, then that is the reason why your local code works smooth.

## 2. QA server problem.

** Question is: **
- What url does your IMGKit code request to generate image ? 
- Where does the url point to?
- Does the url point to an `action` in `controller` of your QA?
- How many processes or threads  of your QA server?

I can't determine the answer without those information.
